"""add answer_runs table

Revision ID: f9b3096dcc21
Revises: 59c065a343c6
Create Date: 2026-07-23 23:52:54.776151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b3096dcc21'
down_revision: Union[str, Sequence[str], None] = '59c065a343c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_runs',
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('retrieval_mode', sa.String(), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('min_score', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('retrieved_chunk_ids', sa.Text(), nullable=False),
    sa.Column('citations', sa.Text(), nullable=False),
    sa.Column('retrieval_ms', sa.Float(), nullable=True),
    sa.Column('generation_ms', sa.Float(), nullable=True),
    sa.Column('total_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_runs')
    # ### end Alembic commands ###